from __future__ import annotations

import argparse
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path


CREATE_SNAPSHOTS_TABLE = """
CREATE TABLE IF NOT EXISTS snapshots (
    date TEXT PRIMARY KEY,
    total_value REAL NOT NULL,
    source_file TEXT NOT NULL,
    inserted_at TEXT NOT NULL
)
"""

CREATE_HOLDINGS_TABLE = """
CREATE TABLE IF NOT EXISTS holdings (
    snapshot_date TEXT NOT NULL,
    asset_name TEXT NOT NULL,
    asset_type TEXT NOT NULL,
    value REAL NOT NULL,
    PRIMARY KEY (snapshot_date, asset_name, asset_type),
    FOREIGN KEY (snapshot_date) REFERENCES snapshots(date) ON DELETE CASCADE
)
"""

CREATE_HOLDINGS_INDEX = """
CREATE INDEX IF NOT EXISTS idx_holdings_snapshot_date
ON holdings(snapshot_date)
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Ingest parsed NSDL CAS JSON snapshots into SQLite.",
    )
    parser.add_argument(
        "--json-dir",
        default="parsed_json",
        help="Directory containing JSON files generated by parse.py.",
    )
    parser.add_argument(
        "--db-path",
        default="data/net_worth.db",
        help="SQLite database path.",
    )
    return parser.parse_args()


def create_schema(connection: sqlite3.Connection) -> None:
    connection.execute("PRAGMA foreign_keys = ON")
    connection.execute(CREATE_SNAPSHOTS_TABLE)
    connection.execute(CREATE_HOLDINGS_TABLE)
    connection.execute(CREATE_HOLDINGS_INDEX)
    connection.commit()


def list_json_files(json_dir: Path) -> list[Path]:
    return sorted(path for path in json_dir.iterdir() if path.is_file() and path.suffix.lower() == ".json")


def snapshot_exists(connection: sqlite3.Connection, statement_date: str) -> bool:
    query = "SELECT 1 FROM snapshots WHERE date = ? LIMIT 1"
    return connection.execute(query, (statement_date,)).fetchone() is not None


def validate_payload(payload: dict, source_path: Path) -> tuple[str, float, list[dict]]:
    statement_date = payload.get("statement_date")
    total_value = payload.get("total_portfolio_value")
    holdings = payload.get("holdings", [])

    if not statement_date:
        raise ValueError(f"Missing statement_date in {source_path.name}")
    if total_value is None:
        raise ValueError(f"Missing total_portfolio_value in {source_path.name}")
    if not isinstance(holdings, list):
        raise ValueError(f"Invalid holdings payload in {source_path.name}")

    return statement_date, float(total_value), holdings


def ingest_file(connection: sqlite3.Connection, json_path: Path) -> str:
    payload = json.loads(json_path.read_text(encoding="utf-8"))
    statement_date, total_value, holdings = validate_payload(payload, json_path)

    if snapshot_exists(connection, statement_date):
        return f"Skipped {json_path.name}: duplicate snapshot for {statement_date}"

    inserted_at = datetime.now(timezone.utc).isoformat()
    source_file = payload.get("source_file", json_path.name)

    with connection:
        connection.execute(
            """
            INSERT INTO snapshots(date, total_value, source_file, inserted_at)
            VALUES (?, ?, ?, ?)
            """,
            (statement_date, total_value, source_file, inserted_at),
        )

        connection.executemany(
            """
            INSERT INTO holdings(snapshot_date, asset_name, asset_type, value)
            VALUES (?, ?, ?, ?)
            """,
            [
                (
                    statement_date,
                    str(holding["name"]).strip(),
                    str(holding["type"]).strip(),
                    float(holding["value"]),
                )
                for holding in holdings
                if holding.get("name") and holding.get("type") and holding.get("value") is not None
            ],
        )

    return f"Ingested {json_path.name}: {statement_date}"


def main() -> None:
    args = parse_args()
    json_dir = Path(args.json_dir).expanduser().resolve()
    db_path = Path(args.db_path).expanduser().resolve()
    db_path.parent.mkdir(parents=True, exist_ok=True)

    if not json_dir.exists():
        raise FileNotFoundError(f"JSON directory does not exist: {json_dir}")

    json_files = list_json_files(json_dir)
    if not json_files:
        raise FileNotFoundError(f"No JSON files found in {json_dir}")

    with sqlite3.connect(db_path) as connection:
        create_schema(connection)
        for json_path in json_files:
            print(ingest_file(connection, json_path))

    print(f"SQLite database ready at {db_path}")


if __name__ == "__main__":
    main()
